# Generated by Django 4.1 on 2022-08-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionID', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('option1', models.CharField(default='', max_length=50)),
                ('option2', models.CharField(default='', max_length=50)),
                ('option3', models.CharField(default='', max_length=50)),
                ('option4', models.CharField(default='', max_length=50)),
                ('correctOption', models.CharField(default='', max_length=50)),
                ('delete', models.BooleanField(default=False)),
                ('scoreSlider', models.IntegerField(default=0)),
            ],
        ),
    ]
