# Generated by Django 4.1 on 2022-08-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_question_questionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionID',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
